// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbleuNSDYzU3SEIaDkZJ5fcdSvnkBu4Hk',
    appId: '1:373651944894:web:c50c89941dd6b40e8bf5ef',
    messagingSenderId: '373651944894',
    projectId: 'smart-elfaize',
    authDomain: 'smart-elfaize.firebaseapp.com',
    storageBucket: 'smart-elfaize.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIKV7l0e6M7UvVikpMXnndZaUqhBVq4ro',
    appId: '1:373651944894:android:d2ef42d6cd01d5028bf5ef',
    messagingSenderId: '373651944894',
    projectId: 'smart-elfaize',
    storageBucket: 'smart-elfaize.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbleuNSDYzU3SEIaDkZJ5fcdSvnkBu4Hk',
    appId: '1:373651944894:web:262e5fb015ab2b3b8bf5ef',
    messagingSenderId: '373651944894',
    projectId: 'smart-elfaize',
    authDomain: 'smart-elfaize.firebaseapp.com',
    storageBucket: 'smart-elfaize.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC44A65ViwpCbcRrYt-ZxA8xml5Fknv19E',
    appId: '1:373651944894:ios:583b673768fddb288bf5ef',
    messagingSenderId: '373651944894',
    projectId: 'smart-elfaize',
    storageBucket: 'smart-elfaize.firebasestorage.app',
    iosBundleId: 'com.example.smartAppElfaize',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC44A65ViwpCbcRrYt-ZxA8xml5Fknv19E',
    appId: '1:373651944894:ios:583b673768fddb288bf5ef',
    messagingSenderId: '373651944894',
    projectId: 'smart-elfaize',
    storageBucket: 'smart-elfaize.firebasestorage.app',
    iosBundleId: 'com.example.smartAppElfaize',
  );

}